# console
model_cfg:
  name: 'esp'
  future_steps: 50
  mode_num: 8
  gamma: 1.

planner: 
  name: 'esp'

  cov_base: [0.1, 0.005]
  cov_inc: [0., 0.] #1.e-4
  const_turb: True
  gt_sample_num: 30
  plan_sample_num: 200

  meter2risk: 
    name: 'CostModelTV'
    V_dim: 9
    th: 50
    # input_shape: 256
    # TVC: False
    # idv: True
  loss:
    dis_prob: False
    gt_label: True #not recomended
    nmp_loss: False