planner: 
  name: 'base'
  time_horizon: 50
  time_interval: 0.1
  feature_count: 9
  trajectory_len: 50 
  feature_len: 9
  cost_items: 3
  num_functions: 1 #+-log, +-exp,1/x,sigmoid,x^2,x
  sdf_index_ratio: [1.,1.]
  ego_center: [30,35]
  lagrange_dim: 4
  reflane_interpolating_factor: 2 #SET ZERO TO DISABLE
  sdf_interpolating_factor: 1
  u_dim: 2
  default_v: 20 # m/s

  train_sampler_config: 'utils/riskmap/mpp/frenet_sampler.train.json'
  test_sampler_config: 'utils/riskmap/mpp/frenet_sampler.train.json'

  meter2risk: 
    name: 'deep_cost'
    TVC: False
    V_dim: 8
    input_shape: 256
    th: 1
    idv: True

  strict_filter:
    enable: True
    v_lim: 25
    a_lim: 8
  
  making_sample:
    enable: True
    make_range_x: 5
    make_range_y: 2.7
    make_num_x: 20
    make_num_y: 20

  risk_preference: [1.0,1.0,1.0,1.0,1.0,1.0,1.0]

  loss:
    loss_CE: True
    loss_var: False
    loss_reg: False
    loss_GT_l1: False
    loss_idv: False
    loss_END: False
    loss_cost_GT: False