# console
model_cfg:
  name: 'risk'
  future_steps: 50
  mode_num: 8
  gamma: 0.99
  time_embedding: True

planner: 
  name: 'risk'
  time_horizon: 50 # same as future_steps

  cov_base: [0.2, 0.2]
  cov_inc: [0., 0.] #1.e-4
  const_turb: True
  gt_sample_num: 30
  plan_sample_num: 200 # no less than 200
  lattice_sampler: True
  collision_check: False
  train_genetic: 3
  inference_genetic: 10

  meter2risk: 
    name: 'CostModel'
    V_dim: 6
    th: 50
    # input_shape: 256
    # idv: True
    # TVC: False
  
  loss:
    dis_prob: True
    gt_label: False #not recomended
    nmp_loss: False
  
  risk_preference: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
