# console
model_cfg:
  name: 'risk'
  future_steps: 50
  mode_num: 8

planner: 
  name: 'risk'
  cov_base: 0.2
  cov_inc: 1.e-4
  gt_sample_num: 150
  plan_sample_num: 200

  meter2risk: 
    name: 'CostModel'
    TVC: False
    V_dim: 8
    input_shape: 256
    th: 1
    idv: True
  
  risk_preference: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
